### PR TITLE
Creating Javadocs and updating parameters

### PR DESCRIPTION
**Pull request by darpanmishra**
**_Changes_**

- Created Javadocs for usecases that were not specified previously.
- Added to parameters that were not clearly defined and created full docstrings.

### CODE REVIEW

**Review by nathan-cai — DISMISSED** [review]
Great Job writing Javadovs. The descriptions seem clear, concise, and east to understand.

**Review by aryangoel24 — APPROVED** [review]
Good job writing the java doc for the use case interactors

**Review by Akshayan03 — APPROVED** [review]
Well done on creating doc strings for all of these use cases to greatly and more deeply explain what these methods do and what their functionality does to make it more clear for any users that are looking at the code and want to use the methods

**Review by aryangoel24 — APPROVED** [review]
Good job writing the java doc for the use case interactors

**Review by aryangoel24 — APPROVED** [review]
good job resolving the conflicts and creating the java docs for the use case interactors

**Review by Akshayan03 — APPROVED** [review]
Well done on creating doc strings for all of these use cases to greatly and more deeply explain what these methods do and what their functionality does to make it more clear for any users that are looking at the code and want to use the methods

**Review by manndthakkar — APPROVED** [review]
Great that you added Javadocs, hence improving the code documentation

**Pull request merged**
