### PR TITLE
Implemented Clean Architecture for Login Usecase

### PR DESCRIPTION
**Pull request by nathan-cai**
**Changes**

- Created Login Presenter
- Created Login Controller
- Implemented LoginResultLabel that implements Login Presenter
- Add Presenter to Login Presenter
- Implemented Clean Architecture for the Login Presenter Usecase

### CODE REVIEW

**Comment by aryangoel24** [comment]
i notice that you removed the price ranges numbers near the price range texts, i believe this was to resolve a bug, but upon checking it out locally this did not make a difference. The bug was originating from another issue which has been resolved, so no need to remove it anymore

**Review by Akshayan03 — APPROVED** [review]
Well done on your implementation of clean architecture on the login use case looks like you've done a great job adhering to clean architecture, but as Aryan said I also noticed that you removed the price ranges numbers near the price range texts, so you should change this

**Review by aryangoel24 — APPROVED** [review]
Great job implementing clean architecture for the login use case

**Review by Akshayan03 — APPROVED** [review]
Well done on your implementation of clean architecture on the login use case looks like you've done a great job adhering to clean architecture, but as Aryan said I also noticed that you removed the price ranges numbers near the price range texts, so you should change this

**Review by vandanppatel — APPROVED** [review]
Looks good. Good job adding controllers and gateways for clean architecture.

**Pull request merged**
