### PR TITLE
Implemented priceFilter class use case implementation. Following stru…

### PR DESCRIPTION
**Pull request by darpanmishra**
…cture of restaurantFilter and connected to filterManager class that will be utilized in GUI.

### CODE REVIEW

**Comment by nathan-cai** [comment]
The Arraylist should be an Arraylist<foodItem> because you are filtering the menu.

**Comment by nathan-cai** [comment]
filterName instance variable is redundant because there is only 1 price filter.

**Comment by nathan-cai** [comment]
Remove the Restaurant Class import

**Review by nathan-cai — APPROVED** [review]
Looks good!

**Review by aryangoel24 — APPROVED** [review]
Great job implementing the price filter use case, everything looks in order. maybe we can try to be more clear with the naming conventions though, for example we could change p_range to price_range to be more explicit

**Review by manndthakkar — APPROVED** [review]
Changes look good except the naming convention that you have used at some places (e.g: p_range)

**Pull request merged**
