### PR TITLE
Budget manager

### PR DESCRIPTION
**Pull request by Akshayan03**

### CODE REVIEW

**Review by aryangoel24 — CHANGES_REQUESTED** [review]
Everything looks great but given that we have getter methods and setter methods for initialBudget and currentBudget, we should make initialBudget and currentBudget either private or protected attributes.

**Review by darpanmishra — CHANGES_REQUESTED** [review]
Looks good.
But I think we should have the initial and current budget set to be a large amount so that even if the user does not input a desired budget they still have access to all the features of the model.
Either we can set the initial budget to be infinite or an extremely large number that would not be in the scope of a real budget.

**Review by nathan-cai — APPROVED** [review]
Looks Good

**Review by darpanmishra — APPROVED** [review]
Looks good now.

**Review by aryangoel24 — APPROVED** [review]
Looks great, good idea changing the empty constructor to set initial and current budget to 1000000 as this ensures our app does not fail if a user does not enter a budget. All the subsequent methods look great too.

**Pull request merged**
