### PR TITLE
Implementing data access interfaces

### PR DESCRIPTION
**Pull request by aryangoel24**
Created data access interfaces for the database to implement to fit with clean architecture

Refactored all the areas where the database was being used directly, files changed include:
- FilterManagerController
- LogicCode
- Login
- SuggestionToUser
- SuggestionToUserTest

Changed the restaurantEntityTest to not use the database at all, and just test the restaurant getter methods on local objects to fit with the other entity tests formats.

### CODE REVIEW

**Review by Akshayan03 — DISMISSED** [review]
Well done on creating the data access interfaces for the database so that it is able to be implemented in order to adhere clean architecture. Well done on adjusting the restaurantEntityTests so that they no longer depend on mainmongoDB

**Review by Aviral-03 — CHANGES_REQUESTED** [review]
Please put MainMongoDB file into Gateway package, because it is currently in the UseCase package.

**Review by Aviral-03 — CHANGES_REQUESTED** [review]
orderEntityTest is empty?

**Review by Akshayan03 — APPROVED** [review]
Great job on creating the data access interfaces for the database so that it is able to be implemented in order to adhere clean architecture. Well done on adjusting the restaurantEntityTests so that they no longer depend on mainmongoDB

**Review by Aviral-03 — APPROVED** [review]
Everything looks good. Nice to see that you have identified Clean Architecture principles and followed it such as Data Access Interface and Gateways. Good job on packaging as well.

**Review by JanelGilani — APPROVED** [review]
This PR has made major packaging changes and you have done a great job refactoring every instance where the database was being called. The changed files clearly follow the Clean Architecture layers and the dependency between the use case interactors and the database has been removed using an interface to follow the dependency rule.

**Pull request merged**
