### PR TITLE
Created entity tests for Order, PastOrders, ItemCart. Created tests for MainMongoDB. 

### PR DESCRIPTION
**Pull request by aryangoel24**
Created all the tests for Order, PastOrders, ItemCart
Added getCurrentOrder method to ItemCart
Rearranged methods in each of these classes so that getters are at the top, followed by rest of functions
Added deleteUser and deleteRestaurant methods to MainMongoDB for the tests
Created multiple tests for the MainMongoDB class as well

### CODE REVIEW

**Review by Akshayan03 — DISMISSED** [review]
Nice job on creating the tests for the entity cases that we had remaining and also for the mainmongodb file. The tests look very well done to me as they follow the typical structure of tests in Java, however I do see some code smells in some tests with certain imports not being used such as in the past order entity test file and also make sure to check your intelliji test coverage report to get somewhere from 80-90%

**Review by JanelGilani — DISMISSED** [review]
Great job refactoring and re-arranging the methods in ItemCart, Order and PastOrders entities. You have made smart use of @Before and @After annotations to ease the testing process for database access. However, the makeOrder method is actually called in the Make Order use case so it would be more relevant to test when testing MakeOrderInteractor.

**Review by JanelGilani — APPROVED** [review]
Great job refactoring and re-arranging the methods in ItemCart, Order and PastOrders entities. You have made smart use of @before and @after annotations to ease the testing process for database access. However, the makeOrder method is actually called in the Make Order use case so it would be more relevant to test when testing MakeOrderInteractor. Additionally, be sure to do the MongoDB with the updated DAI.

**Review by Akshayan03 — APPROVED** [review]
Nice job on creating the tests for the entity cases that we had remaining and also for the mainmongodb file. The tests look very well done to me as they follow the typical structure of tests in Java, however I do see some code smells in some tests with certain imports not being used such as in the past order entity test file and also make sure to check your intelliji test coverage report to get somewhere from 80-90%

**Review by manndthakkar — APPROVED** [review]
New tests for the entities and mongo db methods look good.

**Pull request merged**
