### PR TITLE
Edited foodItem, itemCart, Order and pastOrder classes

### PR DESCRIPTION
**Pull request by aryangoel24**
Added restaurant instance attribute to foodItem and Order classes, changed all instance attributes in foodItem, itemCart, Order and pastOrders from public to protected, and added getter methods to each class.

### CODE REVIEW

**Review by manndthakkar — DISMISSED** [review]
Its good that you have changed all public instance variables to protected, and added getter and setter functions. Could we also have getter method for the restaurant in the Order entity?

**Review by JanelGilani — COMMENTED** [review]
ignore

**Review by JanelGilani — APPROVED** [review]
I think it looks good, its always good to have protected instance variables and getter functions can be used if any other classes need to access those variables.

**Review by darpanmishra — DISMISSED** [review]
Looks good to me.

**Review by manndthakkar — APPROVED** [review]
Its good that you have changed all public instance variables to protected, and added getter and setter functions

**Review by Akshayan03 — APPROVED** [review]
looks good

**Review by Akshayan03 — APPROVED** [review]
looks good

**Review by nathan-cai — COMMENTED** [review]
Looks Good

**Review by nathan-cai — APPROVED** [review]
Looks Good

**Pull request merged**
