### PR TITLE
Class Name and Packaging Convention Changes

### LINKED ISSUE #157: Final Refactoring for Class Names and Packages
Edit class names and packaging structure to adhere to the Clean Architecture packaging strategy.
Edit all the files to add Javadocs, and comments and dealt with IntelliJ warnings.

### PR DESCRIPTION
**Pull request by JanelGilani**
Edited class names and packaging structure to adhere to the Clean Architecture packaging strategy.
Edited all the files to add Javadocs, and comments and dealt with IntelliJ warnings.

### CODE REVIEW

**Review by darpanmishra — DISMISSED** [review]
Looks good to me! Great job implementing the final refactoring and packaging convention changes for our project.

**Review by Akshayan03 — DISMISSED** [review]
Brilliant job of looking over and correcting all the classes we had for our project to ensure that we now longer have any code smells regarding unused code and well done on the packaging and class name changes to follow the proper documentation styles

**Review by Akshayan03 — APPROVED** [review]
Brilliant job of looking over and correcting all the classes we had for our project to ensure that we now longer have any code smells regarding unused code and well done on the packaging and class name changes to follow the proper documentation styles

**Review by vandanppatel — APPROVED** [review]
great job editing read me and now that everything is refractored it's easy to navigate from one file to another

**Review by Aviral-03 — APPROVED** [review]
Looks good to me! Great job implementing the final refactoring and packaging convention changes for our project.Looks good to me! Great job implementing the final refactoring and packaging convention changes for our project.

**Pull request merged**
