### PR TITLE
3 restaurant filter

### PR DESCRIPTION
**Pull request by nathan-cai**
Completed Restaurant Filter Use Case. First Dev.

### CODE REVIEW

**Review by darpanmishra — APPROVED** [review]
Looks good to me

**Review by aryangoel24 — COMMENTED** [review]
looks good

**Review by aryangoel24 — COMMENTED** [review]
looks good

**Review by aryangoel24 — APPROVED** [review]
looks good but i think it would be better to be more precise in your getter methods, by returning this.cuisinePreference etc... since this makes it more clear as to what we are returning

**Review by Akshayan03 — APPROVED** [review]
Changes look good to me, restaurant array for the filter looks well done, having the default preferences as null was also a good touch. Follows the crc cards accordingly and looks implemented well

**Pull request merged**
