### PR TITLE
Implemented the design patterns: RestaurantFactory, UserBuilder, FoodItemIterator, CurrentOrderIterator

### PR DESCRIPTION
**Pull request by aryangoel24**
Implemented the following design patterns:
- RestaurantFactory
- UserBuilder
- FoodItemIterator + CurrentOrderIterator

Added three methods to the ItemCart class to incorporate the CurrentOrderIterator:
- createIterator()
- checkInByIterator(): returns ArrayList of food item names in current order given an iterator
- checkIn(): calls createIterator(), and checkInByIterator() to return an ArrayList of the food item names in current order given no arguments

Created entity test files for RestaurantFactory, and UserBuilder

Added to ItemCartEntityTest to test the checkIn method

### CODE REVIEW

**Review by Akshayan03 — APPROVED** [review]
Well done on creating and implementing design patterns throughout our project wherever you felt necessary, as that was an important part of the rubric that Amogh had told us to focus on as we were severely lacking in this throughout our program and it's good that we started to implement them and good stuff on creating the files for the entity tests for RestaurantFactory, and UserBuilder that we will now have to implement

**Review by Aviral-03 — APPROVED** [review]
Great use of design pattern. It was essential for us to use these patterns such as Factory to create restaurants for listing and Iterator. These greatly contribute in making our project adhere to Clean Architecture functionality. Good catch of making tests for these as well as it would help us to test these functions.

**Review by Akshayan03 — APPROVED** [review]
Well done on creating and implementing design patterns throughout our project wherever you felt necessary, as that was an important part of the rubric that Amogh had told us to focus on as we were severely lacking in this throughout our program and it's good that we started to implement them and good stuff on creating the files for the entity tests for RestaurantFactory, and UserBuilder that we will now have to implement

**Review by JanelGilani — APPROVED** [review]
You have done well to consider the feedback given in milestone 4 to implement relevant design patterns to improve the readability and scope of modification of the program.

**Pull request merged**
