### PR TITLE
Small Change

### PR DESCRIPTION
**Pull request by Aviral-03**
Deleted main method of MongoDB file.

### CODE REVIEW

**Review by nathan-cai — DISMISSED** [review]
Good Catch!

**Review by manndthakkar — APPROVED** [review]
Great

**Review by aryangoel24 — APPROVED** [review]

**Review by Akshayan03 — APPROVED** [review]
Well done on catching this change early and making the needed changing to the program

**Review by darpanmishra — APPROVED** [review]
Good catch, this might have caused us alot of issues later if we tried running the UI with implementation of Mongo.

**Pull request merged**
