### PR TITLE
Restaurant Entity + UserLogin Initial Implementation on main file

### PR DESCRIPTION
**Pull request by darpanmishra**
Changed all public instances of Restaurant to protected instance attributes.
Also created main getter methods for Restaurant class.

### CODE REVIEW

**Comment by darpanmishra** [comment]
Restaurant Entity changes, making instance attributes protected and adding getter methods.
Initial implementation of user login using Jswing done on main file.

**Comment by darpanmishra** [comment]
Implementation is on main file but will later be properly categorized into different files based on the page it correlates to for a cleaner look.
Commented previous code from Mann, for OnboardingFrame.

**Review by manndthakkar — APPROVED** [review]
Looks good!

**Review by Aviral-03 — APPROVED** [review]
LGTM!

**Review by aryangoel24 — APPROVED** [review]
Looks great but we need to separate the different frames into different files in the frames folder as opposed to putting them in the main

**Pull request merged**
