### PR TITLE
Moved the code for UI from main.java to a new LoginFrame.java

### PR DESCRIPTION
**Pull request by manndthakkar**

### CODE REVIEW

**Review by darpanmishra — APPROVED** [review]
Looks good for now, we need to make sure that we can later implement the override method properly and use the action listener method to compare login attempts.
Also good job with the Login naming convention.

**Review by Akshayan03 — APPROVED** [review]
Looks good so far, great start on the UI design, still got more to finish

**Comment by vandanppatel** [comment]
This looks good, great start to the UI. Will use this as a way to visualize my sign up sign in code.

**Review by vandanppatel — APPROVED** [review]
This looks good, great start to the UI. Will use this as a way to visualize my sign up sign in code. Will ensure to keep the nomenclature the same for my code.

**Pull request merged**
