### PR TITLE
Created TestDAI, and implemented MainMongoDBTest

### PR DESCRIPTION
**Pull request by aryangoel24**
… MainMongoDBTest file. MainMongoDB now also implements this interface.

Updated PastOrders method getCostOfLastOrdered to use getter method of order instead of accessing the instance attribute directly.

Changed addToPastOrders method in MainMongoDB as it was not working due to a typo.

Added getMenuTest to restaurantEntityTest

### CODE REVIEW

**Review by Akshayan03 — APPROVED** [review]
Well done on the MainMongoDBTest file and making it so that it implements this interface. Updating the PastOrders method for getCostOfLastOrdered to use the getter method of order instead of accessing the instance attribute directly was also a well-needed adjustment that we needed to do and also good job on fixing the rest of the bugs you had

**Review by Aviral-03 — APPROVED** [review]
Good test coverage, making test for Database. This was essential to ensure that our data base are not dependent on Use Case tests.

**Review by JanelGilani — APPROVED** [review]
You have done a great job by creating comprehensive test cases for the newly implemented Data Access Interfaces for the use cases. You have also made sure to refactor the tests for MainMongoDB.

**Review by JanelGilani — APPROVED** [review]
You have done a great job by creating comprehensive test cases for the newly implemented Data Access Interfaces for the use cases. You have also made sure to refactor the tests for MainMongoDB.

**Review by Akshayan03 — APPROVED** [review]
Well done on the MainMongoDBTest file and making it so that it implements this interface. Updating the PastOrders method for getCostOfLastOrdered to use the getter method of order instead of accessing the instance attribute directly was also a well-needed adjustment that we needed to do and also good job on fixing the rest of the bugs you had

**Review by Aviral-03 — APPROVED** [review]

**Review by Aviral-03 — APPROVED** [review]

**Pull request merged**
