### PR TITLE
Implement ItemCart UI

### PR DESCRIPTION
**Pull request by nathan-cai**
**Changes**

- Created ItemCartPresenter Interface
- Created ItemCartInteractor
- Created ItemCartController
- Created ItemCart Frame with buttons to go back and remove items from item cart
- Added remove from Cart Method to itemCart entity
- Added ItemCartController to FoodItemsFrame
- Allow FoodItemsFrame to add foods to item cart and link to the ItemCartFrame

**Next Step**

- Figure out how to create a new order

### CODE REVIEW

**Review by manndthakkar — DISMISSED** [review]
Looks like you have made a lot of changes on your branch without updating your branch from the main since the start. Please do so before pushing, and see if you need to make any other changes/updates to your code.

**Review by aryangoel24 — APPROVED** [review]
Great job implementing the ItemCart functionality onto the UI, it looks great

**Review by Akshayan03 — APPROVED** [review]
Well done on creating everything needed for item cart and adhering to clean architecture on every step

**Review by manndthakkar — APPROVED** [review]
Great that you added the Item cart frame keeping Clean Architecture in mind, while also connecting the UI to the backend.

**Pull request merged**
