### PR TITLE
The Login Frame now linked with Login and Mongo DB

### PR DESCRIPTION
**Pull request by vandanppatel**
The Login, LoginFrame and MongoDB are now all linked together. The Login frame should now be functional

### CODE REVIEW

**Review by Akshayan03 — CHANGES_REQUESTED** [review]
Nice job on connecting the UI to the backend of your login but your description for this PR is horrible and not following the standards that amigo told us please fix

**Review by aryangoel24 — APPROVED** [review]
good job implementing the login with the ui, and noticing the necessary if statement in the PastOrders class. Also, nice job noticing the dead files CurrentUser and NewUser

**Review by manndthakkar — APPROVED** [review]
Good job deleting the CurrentUser and NewUser files, as they were never used. Also good job, connecting the LoginFrame to the database.

**Review by Akshayan03 — APPROVED** [review]
great job on adding the implementation of connecting the Ui to the backend of your login use case

**Pull request merged**
