### PR TITLE
Packaging by Clean Architecture Layers

### PR DESCRIPTION
**Pull request by JanelGilani**
Organized packages based on which layer of CA they belong to
Made new packages for controllers and gateways
Renamed all packages to lowercase
Renamed all classes to follow java packaging rules
Removed tutorial package, and all other unused packages and files
Made ItemCart and PastOrders entities and added 'makeorder' use case.

### CODE REVIEW

**Review by aryangoel24 — APPROVED** [review]
Great job incorporating the feedback from Milestone 4, and refactoring all the code to ensure that the code satisfies the CA principles. Also, great job in refactoring the package and class names, and resolving the necessary conflicts, that will be a great time saver in the future.

**Review by Akshayan03 — APPROVED** [review]
Nice job on using the feedback we received from the milestone 4 rubric in order to clean up the files and make sure that they adhere with clean architecture. Refactoring the package and class names were things that the TA told us to notice and change as they are small yet important things and you've managed to fix the mistakes here while simultaneously  resolving the necessary conflicts

**Review by aryangoel24 — APPROVED** [review]
great job refactoring all the code, for the non-working tests, i will refactor the database code too

**Review by darpanmishra — APPROVED** [review]
Good job with fixing the packaging and fixing/refractoring all the naming convention issues that we had.
What we can focus on now is making sure all the tests pass and we should be good.
Great work!

**Review by manndthakkar — APPROVED** [review]
The tests seems to fail due to a mongoDB refactoring issue. Apart from that, the changes to the file names, and naming conventions looks good.

**Pull request merged**
