### PR TITLE
Edited Bugs in BudgetManager use case and Budget Entity and created tests for Budgetmanager use case and restaurant and budget entity

### PR DESCRIPTION
**Pull request by Akshayan03**
Polished up the budget entity and budget manager by cleaning up the class and adhering to clean architecture 
Updated all the methods, so that they all work accordingly and have made multiple tests for each one of the methods of the use case budgetManager,
Have also updated the Budget entity by re-adding the set initial budget setter function as it was needed for the new implementation of the adjust budget feature
Also added tests for restaurant entity, and budget entity covering all the methods in the respected entities

### CODE REVIEW

**Review by Aviral-03 — COMMENTED** [review]
Compared to the previous iteration why did you remove the exception cases, which throws an error when an illegal input is given?

**Review by Aviral-03 — APPROVED** [review]
Great that you worked on the feedback given, and included Error Messages. Looks great, hope all the test are working. Now after packaging pull request is approved, kindly work on the Clean Architecture by organizing your code according to controllers and presenters.

**Comment by Aviral-03** [comment]
> Compared to the previous iteration why did you remove the exception cases, which throws an error when an illegal input is given?

Compeleted

**Review by aryangoel24 — APPROVED** [review]
Changes look great, great job implementing the feedback given. Your tests look good too, but for the budgetEntityTest I noticed that you are testing a lot of duplicates for example getInitialBudgetTest and getUserInitialBudgetTest. These tests are almost identical, where the latter is more testing the database rather than the budget entity, so it may make sense to move these tests to another file. But for now, everything looks great!

**Pull request merged**
