### PR TITLE
Created organised folders and files to incorporate Clean Architecture

### PR DESCRIPTION
**Pull request by JanelGilani**
Created organised folders and files to incorporate Clean Architecture and corresponding layers.

### CODE REVIEW

**Review by Akshayan03 — DISMISSED** [review]
Good adherence to clean architecture and cleaning up the files, so it follows the clean architecture and solid principles. Also, good job on checking on code smells such as bloaters formed due to large classes, taking care of that will help us in the future. Also well done on deleting any lazy classes which were dispensable

**Review by nathan-cai — APPROVED** [review]
Good Organization. The classes look they adhere to the clean architecture principles. Will start implementing the functions

**Review by nathan-cai — APPROVED** [review]
I removed conflicts. The code looks structured properly for clean architecture.

**Review by darpanmishra — APPROVED** [review]
Looks good, working on the clean architecture files will help us better oragnize our code in our use cases and we can also help model all our other files based on the structure we use for this.

**Review by aryangoel24 — APPROVED** [review]
Everything looks great, good job solving the conflicts

**Pull request merged**
