### PR TITLE
Created temp userSuggestionFrame, to be utilized for userSuggestions 

### PR DESCRIPTION
**Pull request by darpanmishra**
_**Features**_

- A skeleton JPanel that will be used for userSuggestions.
- A scrollable JPanel, and ability to add a JButton for future implementation.
- Titled frame, "Budget Bites - Suggestions" - can be changed for better naming convention in the future.

### CODE REVIEW

**Review by Akshayan03 — DISMISSED** [review]
Looking over your code the design for the skeleton JPanel that will be used for userSuggestions looks well done and a scrollable JPanel, and yah I agree that we need the ability to add a JButton which can be done in a  future implementation. the name of the frame should also be adjusted to follow the naming convention of "Budget Bites - Suggestions" but I see you've recognized that so it's well done

**Review by JanelGilani — APPROVED** [review]
The new file created is creating an isolated frame for FoodSuggestions but we will need to make sure that this frame is launched through some initiation in previous frames. We could add more features to the frame such as more information about the suggested food items.

**Review by aryangoel24 — APPROVED** [review]
looks like a good starting point for the userSuggestionFrame

**Review by aryangoel24 — CHANGES_REQUESTED** [review]
please implement userSuggestionFrame

**Review by JanelGilani — APPROVED** [review]
The new file created is creating an isolated frame for FoodSuggestions but we will need to make sure that this frame is launched through some initiation in previous frames. We could add more features to the frame such as more information about the suggested food items.

**Review by Akshayan03 — APPROVED** [review]
Looking over your code the design for the skeleton JPanel that will be used for userSuggestions looks well done and a scrollable JPanel, and yah I agree that we need the ability to add a JButton which can be done in a future implementation. the name of the frame should also be adjusted to follow the naming convention of "Budget Bites - Suggestions" but I see you've recognized that so it's well done

**Review by aryangoel24 — APPROVED** [review]
good job implementing the starter code for the userSuggestionFrame

**Pull request merged**
