### PR TITLE
Fooditem and User entity testing and refactoring

### PR DESCRIPTION
**Pull request by darpanmishra**
**_Changes_**

- Created new test files and cases to test the basic functionalities of the two entities, User and FoodItem
- Refactored naming of files and methods to match the proper guidelines and naming conventions.

_Notes_

- We should try to follow this outline for further entity tests so we can remain streamline and have similar outputs for submission.

### CODE REVIEW

**Comment by Aviral-03** [comment]
Please pull the main file, so that updated test will be included in this pull request and the GitHub classroom test will pass.

**Comment by darpanmishra** [comment]
> Please pull the main file, so that updated test will be included in this pull request and the GitHub classroom test will pass.

Completed, please check and approve.

**Review by JanelGilani — APPROVED** [review]
I see that you created tests for every relevant method in FoodItem and User classes in your initial commit, good job fixing the auto-grading error in your latest commits. The tests seem to be thorough and cover all possible edge cases.

**Review by aryangoel24 — APPROVED** [review]
Great job with the entity tests for FoodItem and User, although there is a lot of repetition. It may be more compact to create an init method that initializes the FoodItem and User in the method, and then these objects can be used in the tests, as opposed to creating new FoodItem and User objects for every test.

**Comment by Aviral-03** [comment]
> > Please pull the main file, so that updated test will be included in this pull request and the GitHub classroom test will pass.
> 
> Completed, please check and approve.

Closed with review

**Review by Aviral-03 — APPROVED** [review]
LGTM. Good that you included JavaDoc for tests as well.

**Review by Akshayan03 — APPROVED** [review]
Great job in creating the tests for User and FoodItem entity, however, I would recommend like Aryan said creating an init method that initializes the FoodItem and User in the method, to reduce any duplicate code cause the test class to be unnecessarily large

**Pull request merged**
