### PR TITLE
Created an Interface to be able to access MainMongoDB in Budget manager and refactored methods and tests of budget manager accordingly

### PR DESCRIPTION
**Pull request by Akshayan03**
Created an interface in order to be able to access the MainMongoDB functions in the budget manager use case, so that when getting input from the user, the changes will be dynamically made accordingly to the MainMongoDB and stored A couple edits also done to the methods in BudgetManager to be able to update the database and take input from user and tests were refactored accordingly

### CODE REVIEW

**Review by JanelGilani — DISMISSED** [review]
You have done well to create a data access interface for the use case manipulating the Budget entity. I don't recognise any potential code smells that this change would lead to. I see you have also made tweaks to the names and Javadocs of the files, make sure to add that in the PR description too.

**Review by aryangoel24 — DISMISSED** [review]
Everything looks great, you have done a great job implementing the BudgetDAI, and having MainMongoDB implement it. Additionally, great job noting that BudgetManager should not extend Budget, as BudgetManager itself is not a Budget.

**Comment by Akshayan03** [comment]
***NEW COMMIT***
Refactored interface BudgetDAI, and added a new method to BudgetManager which was needed to compare inputs from the UserChangeBudgetFrame Methods in budget manager use case also had parameters edited to ensure that they take in the correct inputs and UserChangeBudgetFrame was started to be connected to the backend

**Review by manndthakkar — APPROVED** [review]
Great that you connected the budget frame to the backend

**Review by aryangoel24 — APPROVED** [review]
Once again, everything looks great, the conflicts also appear to be resolved.

**Review by JanelGilani — APPROVED** [review]
You have done well to create a data access interface for the use case manipulating the Budget entity. I don't recognise any potential code smells that this change would lead to. I see you have also made tweaks to the names and Javadocs of the files, make sure to add that in the PR description too. The new commit also has relevant Javadocs too.

**Review by aryangoel24 — APPROVED** [review]
great job adding the doc strings for the test, this will be great for documentation

**Pull request merged**
