### PR TITLE
Created Unit Tests for Restaurant Filtering

### PR DESCRIPTION
**Pull request by nathan-cai**
**Created Tests**

- Test Filter Manager with only 1 input
- Test Filter Manager with 2 inputs
- Test Filter Manager with all 3 inputs

Created, ran, and passed 7 tests.

### CODE REVIEW

**Comment by Aviral-03** [comment]
Please pull the main origin, with the updated tests so that the GitHub classroom's tests will pass.

**Review by aryangoel24 — APPROVED** [review]
Good job making the tests for restaurant filtering, looks like it covers all the methods of the FilterManager class. Although you could improve the documentation slightly by adding the @Before tag to your generateFilterManager() method, to specify that this method needs to be run before each of the tests run.

**Review by JanelGilani — APPROVED** [review]
The tests implemented are able to cover every relevant case however, you could improve the names of the tests since most names are overlapping and it can be easy to misread and misinterpret the tests. Also, the test file is currently following camel case but our naming convention is having the first letter capital for each word, so the class should be named "FilterManagerTest" instead.

**Review by darpanmishra — APPROVED** [review]
Great job implementing unit tests to cover all the restaurant fitering methods.
One thing I would suggest is refactoring the naming of the files and tests in order to better align with the namign convention of camelCase that we are keeping throughout the project
Otherwise, well done.

**Pull request merged**
